// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCi556RXvKvgh72iX568qZgoKqcR8QbIO0',
    appId: '1:762814391090:web:1fa703163289d3c565ed2b',
    messagingSenderId: '762814391090',
    projectId: 'thenotes-flutter-app',
    authDomain: 'thenotes-flutter-app.firebaseapp.com',
    storageBucket: 'thenotes-flutter-app.appspot.com',
    measurementId: 'G-0KD59EPS5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GP0nl8Tk_zKrtgQrXowzGeHfawC3o5g',
    appId: '1:762814391090:android:fb257038e2ccd1e965ed2b',
    messagingSenderId: '762814391090',
    projectId: 'thenotes-flutter-app',
    storageBucket: 'thenotes-flutter-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMH7kpcDbKV_W_hMdUyRkgyXglc6hXj7k',
    appId: '1:762814391090:ios:4b8c735e728e931165ed2b',
    messagingSenderId: '762814391090',
    projectId: 'thenotes-flutter-app',
    storageBucket: 'thenotes-flutter-app.appspot.com',
    iosBundleId: 'com.jsyk.thenotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMH7kpcDbKV_W_hMdUyRkgyXglc6hXj7k',
    appId: '1:762814391090:ios:4b8c735e728e931165ed2b',
    messagingSenderId: '762814391090',
    projectId: 'thenotes-flutter-app',
    storageBucket: 'thenotes-flutter-app.appspot.com',
    iosBundleId: 'com.jsyk.thenotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCi556RXvKvgh72iX568qZgoKqcR8QbIO0',
    appId: '1:762814391090:web:765b93071720874365ed2b',
    messagingSenderId: '762814391090',
    projectId: 'thenotes-flutter-app',
    authDomain: 'thenotes-flutter-app.firebaseapp.com',
    storageBucket: 'thenotes-flutter-app.appspot.com',
    measurementId: 'G-T7L46L20YD',
  );
}
